AWSTemplateFormatVersion: "2010-09-09"
Description: "Infrastructure as Code for AWS Lambda function to automatically start and stop AWS services."
Parameters:
  FunctionName:
    Type: String
    Default: "rbcz-auto-start-stop-services"
  FunctionIamRoleName:
    Type: String
    Default: "rbcz-auto-start-stop-services"
  S3Bucket:
    Type: String
  S3Key:
    Type: String
    Default: "app.zip"
Resources:
  IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref FunctionIamRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: "lambda-permissions-ec2"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:StartInstances"
                  - "ec2:StopInstances"
                  - "ec2:DescribeInstances"
                Resource: "*"
        - PolicyName: "lambda-permissions-rds"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "rds:StartDBInstance"
                  - "rds:StopDBInstance"
                  - "rds:DescribeDBInstances"
                Resource: "*"
        - PolicyName: "lambda-permissions-ecs"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ecs:ListClusters"
                  - "ecs:ListServices"
                  - "ecs:DescribeClusters"
                  - "ecs:UpdateService"
                Resource: "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /

  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Ref FunctionName
      Description: "Automatically start and stop AWS services. Trigger using EventBridge cron expression."
      Runtime: "python3.9"
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Handler: "app.handler"
      Role: !GetAtt IAMRole.Arn
      Timeout: 30
  EventBridgeRuleStart:
    Type: "AWS::Events::Rule"
    Properties:
      ScheduleExpression: "cron(0 8 ? * MON,TUE,WED,THU,FRI *)"
      EventPattern:
        source:
          - "aws.events"
        detail-type:
          - "Scheduled Event"
      Targets:
        - Id: !Ref FunctionName
          Arn: !GetAtt LambdaFunction.Arn
          Input: '{"action":"start"}'
  EventBridgeRuleStop:
    Type: "AWS::Events::Rule"
    Properties:
      ScheduleExpression: "cron(0 20 ? * MON,TUE,WED,THU,FRI *)"
      State: "ENABLED"
      EventPattern:
        source:
          - "aws.events"
        detail-type:
          - "Scheduled Event"
      Targets:
        - Id: !Ref FunctionName
          Arn: !GetAtt LambdaFunction.Arn
          Input: '{"action":"stop"}'
