AWSTemplateFormatVersion: "2010-09-09"

Description: "Main template to deploy all resources to automatically start and stop AWS services."

Metadata:
  Author: FilipKamenar
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Application basic information"
        Parameters:
          - NamePrefix
          - Environment
      - Label:
          default: "Step functions scheduler parameters"
        Parameters:
          - StartCronExpression
          - StopCronExpression
      - Label:
          default: "Lambda functions nested stack"
        Parameters:
          - S3Bucket
          - S3KeyLambdaManageServicesSourceCode
          - S3KeyLambdaCheckRdsSourceCode
          - LambdaFunctionsTemplateUrl
      - Label:
          default: "Step functions nested stack"
        Parameters:
          - StepFunctionsTemplateUrl

Parameters:
  NamePrefix:
    Type: String
    Description: "Prefix for all resources."
  Environment:
    Type: String
    Description: Name of the environment.
    AllowedValues:
      - dev
      - tfx1
      - preprod
      - prod
  StartCronExpression:
    Type: String
    Description: "Cron expression for start services scheduler. Example: cron(0 8 ? * MON,TUE,WED,THU,FRI *)"
    Default: "cron(0 8 ? * MON,TUE,WED,THU,FRI *)"
  StopCronExpression:
    Type: String
    Description: "Cron expression for stop services scheduler. Example: cron(0 20 ? * MON,TUE,WED,THU,FRI *)"
    Default: "cron(0 20 ? * MON,TUE,WED,THU,FRI *)"
  S3Bucket:
    Type: String
    Description: "S3 bucket where the source code of Lambda functions is stored."
  S3KeyLambdaManageServicesSourceCode:
    Type: String
    Description: "S3 key for Lambda function source code to start and stop AWS services. Example: manage_services_lambda.zip"
  S3KeyLambdaCheckRdsSourceCode:
    Type: String
    Description: "S3 key for Lambda function source code to check RDS status. Example: check_state_lambda.zip"
  LambdaFunctionsTemplateUrl:
    Type: String
    Description: Object URL of CFN template lambda_functions.yaml in S3 CodeSourceBucket.
  StepFunctionsTemplateUrl:
    Type: String
    Description: Object URL of CFN template step_functions.yaml in S3 CodeSourceBucket.

Resources:
  LambdaFunctions:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Ref LambdaFunctionsTemplateUrl
      Parameters:
        NamePrefix: !Ref NamePrefix
        Environment: !Ref Environment
        S3Bucket: !Ref S3Bucket
        S3KeyLambdaManageServicesSourceCode: !Ref S3KeyLambdaManageServicesSourceCode
        S3KeyLambdaCheckRdsSourceCode: !Ref S3KeyLambdaCheckRdsSourceCode

  StepFunctions:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Ref StepFunctionsTemplateUrl
      Parameters:
        NamePrefix: !Ref NamePrefix
        Environment: !Ref Environment
        LambdaManageServicesArn: !GetAtt LambdaFunctions.Outputs.LambdaManageServicesArn
        LambdaCheckRdsArn: !GetAtt LambdaFunctions.Outputs.LambdaCheckRdsArn
        StartCronExpression: !Ref StartCronExpression
        StopCronExpression: !Ref StopCronExpression
